### ISSUE TITLE
Bbhd 32 1.3.1 problem heat

### ISSUE THREAD

**Issue by JSP1980** [danielnilsson9/bbs-fw#157]
every time I start to drive the engine heats up very quickly until I reach the thermal limit, I only use the accelerator fully in steps 9 all the time and I configure the engine at 32 a with a 52v 31.5ah battery.

**Comment by danielnilsson9** [comment]
I'm not sure I understand you question. You use full throttle all the time at 32A and your motor gets hot? That sounds pretty normal if that is the case.

**Comment by JSP1980** [comment]
Yes that's right, that is to say that if I only stay with the accelerator fully all the time the engine easily reaches 80 degrees celsius and stops after a very short time. If this is normal there will be t  is there a way to use the accelerator all the time without hitting the thermal limit?

**Comment by danielnilsson9** [comment]
I see, how long is a 'short time'? Are we talking a minute or  2?

**Comment by JSP1980** [comment]
I can't say exactly but the last time it made me about  1,553 miles about 5min

**Comment by danielnilsson9** [comment]
Ok, depending on the ambient temperature (I suppose pretty hot, since summer?) I would say that sounds pretty normal... The limiting is there to protect the motor, it might be a bit more restrictive than stock firmware (unsure if there even was any limiting in stock)..

If you want to disable thermal limiting you can disable temperature sensors from the config tool. But you risk destroying your controller/motor

**Comment by JSP1980** [comment]
do you know a way to cool the motor / controller to avoid heating as much as possible?  

I have already installed several heatsinks on the motor and the controller as well as a fan in extraction but it does not seem sufficient.

**Comment by danielnilsson9** [comment]
No idea, I have probably never run full throttle more than a minute so I never hit the limit..
