### ISSUE TITLE
Display showing 00h

### ISSUE THREAD

**Issue by GreyXor** [danielnilsson9/bbs-fw#57]
Hello,
I received the BBSHD 1.5 hardware and I installed bbs-fw 1.1.0.0 on it.
So far everything seems to work but the screen shows `00H` and the engine failure icon flashing.
Via the USB programming cable I don't have any errors log displayed
Do you have any ideas? Thanks

**Comment by danielnilsson9** [comment]
Not really, never heard of error code 00, it's not an error, it is what is reported when everything is ok and bike is stationary. No idea why that would be shown on the display. Which display is it?

**Comment by danielnilsson9** [comment]
Disregard my comment above, I have made a simple error which obviously haven't been discovered since no other display has reported it as an error. I will fix it and release a patch. Status code normal operation is 01 not 00...

If you can, please try the attached firmware file for bbshd to verify your error is resolved.
[bss-fw-1.1.1b.zip](https://github.com/danielnilsson9/bbs-fw/files/9540314/bss-fw-1.1.1b.zip)

**Comment by GreyXor** [comment]
Now display is showing 30h and i can't drive the bike anymore. Nothing happens
and also i cannot flash back to 1.1.0.
When i click "Download" button it receives the MCU only when I turn off the battery. if I turn on nothing happens, if I turn off then it receives the MCU but then it fails because the battery has gone out. any idea what to do?

**Comment by GreyXor** [comment]
No more 00h with 1.1.1b.
FYI now i get after temperature trigger this log `Unknown (5860) in log`

**Comment by danielnilsson9** [comment]
Thanks for reporting, I made a new release to resolve this issue.
Yes, that normal, you will need to update you config tool to read that log.
