### ISSUE TITLE
Motor.c variable definition lvc_volt_x10 is uint8_t not uint16_t

### ISSUE THREAD

**Issue by dav0000000** [danielnilsson9/bbs-fw#61]
Could this be a problem with lvc?

motor.c definition
static uint8_t lvc_volt_x10;

motor.c value assignment with 42 would mean 420 and not fit in uint8_t
lvc_volt_x10 = (uint16_t)lvc_V * 10;

Then used in motor.c function
uint16_t motor_get_battery_lvc_x10()
{
	return lvc_volt_x10;
}

And motor_get_battery_lvc_x10() is called by function apply_low_voltage_limit() in app.c

**Comment by danielnilsson9** [comment]
Damn yes, well no, not a problem with lvc since that calculation is done in configure:
`send_request(OPCODE_LVC, ((uint16_t)lvc_V * ADC_STEPS_PER_VOLT_X10) / 10u);`

Which doesn't use that variable. However that value is saved for use in battery percentage calculation... And that is why it has seemed a bit of when I was testing on my bike... But worked perfectly on the bench (being set at 24V) since I have a 30V power supply.

**Comment by dav0000000** [comment]
motor_get_battery_lvc_x10() is called on line 603 and 607 in app.c so it that would have been getting uint8_t data too.

**Comment by danielnilsson9** [comment]
Yep, I verified, it was not working at all... I patched the just released 1.1.1 version with this fix too.
